### ISSUE TITLE
火狐浏览器加载3dtiles报错

### ISSUE THREAD

**Issue by tpolong** [fuzhenn/3dtiles-issues#11]
![image](https://user-images.githubusercontent.com/13393721/148714510-066ee651-f495-454a-a7ac-03adb8d5443c.png)
火狐版本 95.0.2 (32 位)
maptalks v1.0.0-beta.7
@maptalks/gl v0.64.0 
@maptalks/transcoders.draco v0.63.0 
@maptalks/3dtiles v0.11.1 

报错消息：DataCloneError: The object could not be cloned. 25 4b6026bf-8772-48f8-a22a-d5c91a643863:31
postMessage拷贝数据有问题

**Comment by fuzhenn** [comment]
是因为火狐浏览器不支持Offscreen的2d context，GLTF Loader里对OffscreenCanvas的判断不够全面，解析图片时出错造成的错误。

**Comment by fuzhenn** [comment]
已经解决并发布了
v0.11.3
