### ISSUE TITLE
加载倾斜摄影错误，cesium可以

### ISSUE THREAD

**Issue by liuyanchen1994** [fuzhenn/3dtiles-issues#12]
![image](https://user-images.githubusercontent.com/19524048/161361240-da8ed4d5-f75c-45f2-b6b5-ee6cf2e88e91.png)

**Comment by fuzhenn** [comment]
收到，能否提供一下出错的模型？

**Comment by fuzhenn** [comment]
先帮忙把上面出错的shader错误贴到这里
注意shader信息需要贴全，出错的shader代码太长时，需要按一下更多按钮来显示完整的代码内容

**Comment by liuyanchen1994** [comment]
![image](https://user-images.githubusercontent.com/19524048/161361374-fd83e3c8-6393-483b-b477-ed4449c98c3f.png)

**Comment by liuyanchen1994** [comment]
> 收到，能否提供一下出错的模型？
这个我无法提供，没有这文件权限

**Comment by fuzhenn** [comment]
上面红色的错误堆栈没有用，需要上面黑色的shader代码

**Comment by fuzhenn** [comment]
要是实在不行，可以加我的qq，我远程来看看

**Comment by liuyanchen1994** [comment]
![image](https://user-images.githubusercontent.com/19524048/161361553-a73dc9b5-a9c8-434c-9bc4-0d4f31c82cec.png)

**Comment by liuyanchen1994** [comment]
这段代码么

**Comment by fuzhenn** [comment]
嗯对，这段代码，我看一下

**Comment by fuzhenn** [comment]
要不加我们qq群吧，等会我试着改一下代码，然后发给你帮我测试一下
971657972

**Comment by liuyanchen1994** [comment]
> 要不加我们qq群吧，等会我试着改一下代码，然后发给你帮我测试一下 971657972

好

**Comment by fuzhenn** [comment]
已经解决

**Comment by fuzhenn** [comment]
原因是gl库中对vao的处理bug导致
